"""Build and verify target-native dependency wheelhouses for offline machines."""

from __future__ import annotations

import hashlib
import json
import os
import platform
import shutil
import subprocess
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

from . import __version__
from .bundles import atomic_write_json, atomic_write_text, render_posix_command, render_powershell_command


class OfflineBundleError(RuntimeError):
    pass


Runner = Callable[..., subprocess.CompletedProcess[str]]


_STANDALONE_VERIFY = r'''"""Stdlib-only verifier generated by ddimctl."""
import hashlib
import json
import platform
import sys
from pathlib import Path

root = Path(__file__).resolve().parent
manifest = json.loads((root / "wheelhouse-manifest.json").read_text(encoding="utf-8"))
records = manifest.get("files")
if manifest.get("schema_version") != 1 or not isinstance(records, list) or not records:
    raise SystemExit("invalid wheelhouse manifest")
builder = manifest.get("builder", {})
current_tag = "cp%d%d" % (sys.version_info.major, sys.version_info.minor)
if builder.get("python_tag") != current_tag:
    raise SystemExit("Python tag mismatch: bundle=%s current=%s" % (builder.get("python_tag"), current_tag))
if str(builder.get("system", "")).casefold() != platform.system().casefold():
    raise SystemExit("operating-system mismatch")
if str(builder.get("machine", "")).casefold() != platform.machine().casefold():
    raise SystemExit("machine-architecture mismatch")
expected = set()
for record in records:
    name = record.get("name")
    if not isinstance(name, str) or Path(name).name != name or not name.endswith(".whl"):
        raise SystemExit("unsafe wheel filename: %r" % (name,))
    path = root / "wheels" / name
    if name in expected or not path.is_file() or path.is_symlink():
        raise SystemExit("missing, duplicate, or unsafe wheel: %s" % name)
    expected.add(name)
    digest = hashlib.sha256()
    size = 0
    with path.open("rb") as handle:
        while True:
            chunk = handle.read(1024 * 1024)
            if not chunk:
                break
            size += len(chunk)
            digest.update(chunk)
    if size != record.get("bytes") or digest.hexdigest() != record.get("sha256"):
        raise SystemExit("wheel verification failed: %s" % name)
actual = {path.name for path in (root / "wheels").glob("*.whl")}
if actual != expected:
    raise SystemExit("wheel set differs from manifest")
print("verified %d wheels" % len(expected))
'''


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def _python_tag() -> str:
    return f"cp{sys.version_info.major}{sys.version_info.minor}"


def build_wheelhouse(
    repo_root: str | os.PathLike[str],
    output_dir: str | os.PathLike[str],
    *,
    python_executable: str | os.PathLike[str] = sys.executable,
    include_tracking: bool = False,
    runner: Runner = subprocess.run,
) -> Path:
    """Build a never-overwritten wheelhouse for this builder's OS/arch/Python.

    Cross-platform compiled wheels are deliberately unsupported here. Build on
    a connected machine matching the offline target, then transfer this entire
    directory through the approved route.
    """

    root = Path(repo_root).expanduser().resolve()
    destination = Path(output_dir).expanduser().resolve()
    if not (root / "pyproject.toml").is_file():
        raise FileNotFoundError(f"project pyproject.toml not found under {root}")
    if destination.exists():
        raise FileExistsError(f"refusing to overwrite wheelhouse: {destination}")
    destination.parent.mkdir(parents=True, exist_ok=True)
    staging = destination.parent / f".{destination.name}.building-{uuid.uuid4().hex}"
    staging.mkdir(exist_ok=False)
    wheels = staging / "wheels"
    wheels.mkdir()
    requirement = ".[tracking]" if include_tracking else "."
    argv = (
        str(python_executable),
        "-m",
        "pip",
        "wheel",
        "--disable-pip-version-check",
        "--only-binary=:all:",
        "--wheel-dir",
        str(wheels),
        requirement,
    )
    try:
        result = runner(
            argv,
            cwd=str(root),
            check=False,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        if result.returncode != 0:
            raise OfflineBundleError(
                "pip could not build the wheelhouse:\n"
                + (result.stderr.strip() or result.stdout.strip() or "unknown pip error")
            )
        wheel_files = sorted(wheels.glob("*.whl"), key=lambda path: path.name.casefold())
        if not wheel_files:
            raise OfflineBundleError("pip completed without producing any wheel files")
        if not any(path.name.casefold().startswith("ddim_training_workflow-") for path in wheel_files):
            raise OfflineBundleError("the project wheel is missing from the wheelhouse")

        files = [
            {"name": path.name, "bytes": path.stat().st_size, "sha256": _sha256(path)}
            for path in wheel_files
        ]
        manifest = {
            "schema_version": 1,
            "created_at": datetime.now(timezone.utc).isoformat(),
            "project_version": __version__,
            "include_tracking": include_tracking,
            "builder": {
                "python": sys.version,
                "python_tag": _python_tag(),
                "system": platform.system(),
                "platform": platform.platform(),
                "machine": platform.machine(),
            },
            "files": files,
        }
        atomic_write_json(staging / "wheelhouse-manifest.json", manifest)
        atomic_write_text(staging / "verify.py", _STANDALONE_VERIFY)
        install_argv = (
            "python",
            "-m",
            "pip",
            "install",
            "--no-index",
            "--find-links",
            "wheels",
            f"ddim-training-workflow=={__version__}",
        )
        atomic_write_text(
            staging / "install.sh",
            "#!/usr/bin/env sh\nset -eu\n"
            "SCRIPT_DIR=$(CDPATH= cd -- \"$(dirname -- \"$0\")\" && pwd)\n"
            "cd \"$SCRIPT_DIR\"\npython verify.py\nexec "
            + render_posix_command(install_argv)
            + "\n",
        )
        atomic_write_text(
            staging / "install.ps1",
            "$ErrorActionPreference = 'Stop'\n"
            "Set-Location -LiteralPath $PSScriptRoot\n& 'python' 'verify.py'\n"
            + render_powershell_command(install_argv)
            + "\n",
        )
        destination.parent.mkdir(parents=True, exist_ok=True)
        staging.rename(destination)
        return destination
    except BaseException:
        shutil.rmtree(staging, ignore_errors=True)
        raise


def verify_wheelhouse(bundle_dir: str | os.PathLike[str]) -> dict[str, Any]:
    root = Path(bundle_dir).expanduser().resolve()
    manifest_path = root / "wheelhouse-manifest.json"
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except FileNotFoundError as error:
        raise FileNotFoundError(f"wheelhouse manifest not found: {manifest_path}") from error
    except json.JSONDecodeError as error:
        raise OfflineBundleError(f"invalid wheelhouse manifest: {error}") from error
    if not isinstance(manifest, dict) or manifest.get("schema_version") != 1:
        raise OfflineBundleError("unsupported wheelhouse manifest schema")
    records = manifest.get("files")
    if not isinstance(records, list) or not records:
        raise OfflineBundleError("wheelhouse manifest has no files")
    builder = manifest.get("builder")
    if not isinstance(builder, dict):
        raise OfflineBundleError("wheelhouse manifest has no builder information")
    compatibility = {
        "python_tag": (builder.get("python_tag"), _python_tag()),
        "system": (builder.get("system"), platform.system()),
        "machine": (builder.get("machine"), platform.machine()),
    }
    mismatches = [
        name
        for name, (expected, actual) in compatibility.items()
        if str(expected).casefold() != str(actual).casefold()
    ]
    if mismatches:
        raise OfflineBundleError(
            "wheelhouse is not compatible with this target (mismatch: "
            + ", ".join(mismatches)
            + ")"
        )

    expected_names: set[str] = set()
    total_bytes = 0
    for record in records:
        if not isinstance(record, dict):
            raise OfflineBundleError("invalid wheelhouse file record")
        name = record.get("name")
        if not isinstance(name, str) or Path(name).name != name or not name.endswith(".whl"):
            raise OfflineBundleError(f"unsafe wheel filename in manifest: {name!r}")
        if name in expected_names:
            raise OfflineBundleError(f"duplicate wheel filename in manifest: {name}")
        expected_names.add(name)
        path = root / "wheels" / name
        if not path.is_file() or path.is_symlink():
            raise OfflineBundleError(f"wheel is missing or not a regular file: {name}")
        actual_size = path.stat().st_size
        if actual_size != record.get("bytes"):
            raise OfflineBundleError(f"wheel size mismatch: {name}")
        if _sha256(path) != record.get("sha256"):
            raise OfflineBundleError(f"wheel checksum mismatch: {name}")
        total_bytes += actual_size

    actual_names = {path.name for path in (root / "wheels").glob("*.whl")}
    extras = sorted(actual_names - expected_names)
    if extras:
        raise OfflineBundleError("unrecorded wheel files: " + ", ".join(extras))
    return {
        "path": str(root),
        "files": len(expected_names),
        "bytes": total_bytes,
        "python_tag": builder.get("python_tag"),
        "platform": builder.get("platform"),
        "verified": True,
    }


__all__ = ["OfflineBundleError", "build_wheelhouse", "verify_wheelhouse"]
